export const products = [
  {
    id: "1",
    productImage: "/iphone.jpg",
    productName: "I phone 14 prox max",
    productCategory: "Mobiles",
    productQuantity: "14",
    productPrice: "1400 $",
  },
  {
    id: "2",
    productImage: "/iphone.jpg",
    productName: "I phone 12 prox max",
    productCategory: "Mobiles",
    productQuantity: "5",
    productPrice: "900 $",
  },
  {
    id: "3",
    productImage: "/iphone.jpg",
    productName: "I phone 12 prox max",
    productCategory: "Mobiles",
    productQuantity: "5",
    productPrice: "900 $",
  },
  {
    id: "4",
    productImage: "/iphone.jpg",
    productName: "I phone 12 prox max",
    productCategory: "Mobiles",
    productQuantity: "5",
    productPrice: "900 $",
  },
  {
    id: "5",
    productImage: "/iphone.jpg",
    productName: "I phone 12 prox max",
    productCategory: "Mobiles",
    productQuantity: "5",
    productPrice: "900 $",
  },
  {
    id: "6",
    productImage: "/iphone.jpg",
    productName: "I phone 12 prox max",
    productCategory: "Mobiles",
    productQuantity: "5",
    productPrice: "900 $",
  },
];
